### ISSUE TITLE
Release for http4s 0.23

### ISSUE THREAD

**Issue by perok** [kubukoz/sup#391]
Hi!

Current release of Sup (0.8.1) is on http4s 0.21. Some other upgrades transitively puts us on 0.22 which is not backwards compatible.

I also noticed that 0.9 Milestone depends on http4s 1.0.0-M22, but 0.23 is the first CE3 release.

Would it make sense to have two separate releases of Sup for 0.22 and 0.23? Happy to help out! :)

**Comment by kubukoz** [comment]
Damn, this versioning situation is getting out of hand :joy:

I would probably suggest that you drop the dependency on `sup-http4s` and copy-paste the sources of it while you're on 0.22 (it's just 1-2 files so probably not too much of a maintenance burden).

0.9 final is probably going to use 0.23 as 1.0 isn't going to be released anytime soon (it's just the lack of time for me to bring it down, really), but I'd also wait for Doobie to release a 1.0.0 and Scalacache to update cats-effect so that everything is on more-or-less-stable versions.

**Comment by perok** [comment]
Hehe, yeah! But it will be great when all of this stabilizes :smile: 

Ended up doing as you suggested. It wasn't much work copying the source :)

**Comment by kubukoz** [comment]
Feel free to make a PR going from the 1.0.0 milestones to 0.23 on `main` :)
